AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  
Style/ClassAndModuleChildren:
  Enabled: false
